# Generated by Django 2.0.13 on 2019-03-15 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addressbook', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addressbooklist',
            name='cnumber',
            field=models.BigIntegerField(),
        ),
    ]
