# Generated by Django 2.0.13 on 2019-03-15 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addressbook', '0002_auto_20190315_1533'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addressbooklist',
            name='cnumber',
            field=models.CharField(max_length=12),
        ),
    ]
